[package]
name = "pyaudiocast"
version = "0.1.8"
edition = "2021"

[lib]
name = "_pyaudiocast"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["extension-module"] }
numpy = "0.28"
cpal = "0.17"
ringbuf = "0.4"
hound = "3.5"
log = "0.4"
env_logger = "0.11"
libc = "0.2"

[build-dependencies]
cc = "1"
